version: '3'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 12341234
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "test", "-U", "test"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: ["gunicorn", "djangoproject.wsgi:application", "--bind", "0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
